# Changes here will be overwritten by Copier
_commit: 37f89c1
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: tkp-aliases
project_description: Alias for fsspec-python
project_name: python-fsspec
python_version_primary: '3.11'
team: the python-fsspec authors
